USE habit_tracker_db;

SET @uid = (SELECT user_id FROM users WHERE username = 'demo' LIMIT 1);

-- 5 Habits (mix of types, frequencies, one archived)
INSERT INTO habits (user_id, habit_name, habit_type, goal_quantity, goal_units, frequency, frequency_target, reminder_enabled, reminder_time, is_archived) VALUES
(@uid, 'Morning Run',      'QUANTIFIABLE', 5,  'km',      'DAILY',  1, TRUE,  '07:00', FALSE),
(@uid, 'Drink Water',      'QUANTIFIABLE', 8,  'glasses', 'DAILY',  1, TRUE,  '09:00', FALSE),
(@uid, 'Read Books',       'SIMPLE',       1,  '',        'DAILY',  1, FALSE, NULL,    FALSE),
(@uid, 'Weekly Gym',       'SIMPLE',       1,  '',        'WEEKLY', 3, TRUE,  '18:00', FALSE),
(@uid, 'Old Meditation',   'SIMPLE',       1,  '',        'DAILY',  1, FALSE, NULL,    TRUE);

SET @h1 = (SELECT habit_id FROM habits WHERE user_id=@uid AND habit_name='Morning Run'    LIMIT 1);
SET @h2 = (SELECT habit_id FROM habits WHERE user_id=@uid AND habit_name='Drink Water'   LIMIT 1);
SET @h3 = (SELECT habit_id FROM habits WHERE user_id=@uid AND habit_name='Read Books'    LIMIT 1);
SET @h4 = (SELECT habit_id FROM habits WHERE user_id=@uid AND habit_name='Weekly Gym'    LIMIT 1);
SET @h5 = (SELECT habit_id FROM habits WHERE user_id=@uid AND habit_name='Old Meditation' LIMIT 1);

-- Morning Run: nearly daily for 90 days, a few gaps
INSERT IGNORE INTO completion_logs (habit_id, completion_date) VALUES
(@h1, CURDATE()-INTERVAL 89 DAY), (@h1, CURDATE()-INTERVAL 88 DAY),
(@h1, CURDATE()-INTERVAL 87 DAY), (@h1, CURDATE()-INTERVAL 85 DAY),
(@h1, CURDATE()-INTERVAL 84 DAY), (@h1, CURDATE()-INTERVAL 83 DAY),
(@h1, CURDATE()-INTERVAL 82 DAY), (@h1, CURDATE()-INTERVAL 81 DAY),
(@h1, CURDATE()-INTERVAL 80 DAY), (@h1, CURDATE()-INTERVAL 78 DAY),
(@h1, CURDATE()-INTERVAL 77 DAY), (@h1, CURDATE()-INTERVAL 76 DAY),
(@h1, CURDATE()-INTERVAL 75 DAY), (@h1, CURDATE()-INTERVAL 74 DAY),
(@h1, CURDATE()-INTERVAL 73 DAY), (@h1, CURDATE()-INTERVAL 71 DAY),
(@h1, CURDATE()-INTERVAL 70 DAY), (@h1, CURDATE()-INTERVAL 69 DAY),
(@h1, CURDATE()-INTERVAL 68 DAY), (@h1, CURDATE()-INTERVAL 67 DAY),
(@h1, CURDATE()-INTERVAL 65 DAY), (@h1, CURDATE()-INTERVAL 64 DAY),
(@h1, CURDATE()-INTERVAL 63 DAY), (@h1, CURDATE()-INTERVAL 62 DAY),
(@h1, CURDATE()-INTERVAL 61 DAY), (@h1, CURDATE()-INTERVAL 60 DAY),
(@h1, CURDATE()-INTERVAL 58 DAY), (@h1, CURDATE()-INTERVAL 57 DAY),
(@h1, CURDATE()-INTERVAL 55 DAY), (@h1, CURDATE()-INTERVAL 54 DAY),
(@h1, CURDATE()-INTERVAL 53 DAY), (@h1, CURDATE()-INTERVAL 52 DAY),
(@h1, CURDATE()-INTERVAL 51 DAY), (@h1, CURDATE()-INTERVAL 50 DAY),
(@h1, CURDATE()-INTERVAL 48 DAY), (@h1, CURDATE()-INTERVAL 47 DAY),
(@h1, CURDATE()-INTERVAL 46 DAY), (@h1, CURDATE()-INTERVAL 45 DAY),
(@h1, CURDATE()-INTERVAL 43 DAY), (@h1, CURDATE()-INTERVAL 42 DAY),
(@h1, CURDATE()-INTERVAL 41 DAY), (@h1, CURDATE()-INTERVAL 40 DAY),
(@h1, CURDATE()-INTERVAL 39 DAY), (@h1, CURDATE()-INTERVAL 38 DAY),
(@h1, CURDATE()-INTERVAL 36 DAY), (@h1, CURDATE()-INTERVAL 35 DAY),
(@h1, CURDATE()-INTERVAL 34 DAY), (@h1, CURDATE()-INTERVAL 33 DAY),
(@h1, CURDATE()-INTERVAL 31 DAY), (@h1, CURDATE()-INTERVAL 30 DAY),
(@h1, CURDATE()-INTERVAL 29 DAY), (@h1, CURDATE()-INTERVAL 28 DAY),
(@h1, CURDATE()-INTERVAL 27 DAY), (@h1, CURDATE()-INTERVAL 26 DAY),
(@h1, CURDATE()-INTERVAL 24 DAY), (@h1, CURDATE()-INTERVAL 23 DAY),
(@h1, CURDATE()-INTERVAL 22 DAY), (@h1, CURDATE()-INTERVAL 21 DAY),
(@h1, CURDATE()-INTERVAL 20 DAY), (@h1, CURDATE()-INTERVAL 19 DAY),
(@h1, CURDATE()-INTERVAL 17 DAY), (@h1, CURDATE()-INTERVAL 16 DAY),
(@h1, CURDATE()-INTERVAL 15 DAY), (@h1, CURDATE()-INTERVAL 14 DAY),
(@h1, CURDATE()-INTERVAL 13 DAY), (@h1, CURDATE()-INTERVAL 12 DAY),
(@h1, CURDATE()-INTERVAL 10 DAY), (@h1, CURDATE()-INTERVAL 9 DAY),
(@h1, CURDATE()-INTERVAL 8 DAY),  (@h1, CURDATE()-INTERVAL 7 DAY),
(@h1, CURDATE()-INTERVAL 6 DAY),  (@h1, CURDATE()-INTERVAL 5 DAY),
(@h1, CURDATE()-INTERVAL 4 DAY),  (@h1, CURDATE()-INTERVAL 3 DAY),
(@h1, CURDATE()-INTERVAL 2 DAY),  (@h1, CURDATE()-INTERVAL 1 DAY),
(@h1, CURDATE());

-- Drink Water: daily with small gaps mid-month
INSERT IGNORE INTO completion_logs (habit_id, completion_date) VALUES
(@h2, CURDATE()-INTERVAL 60 DAY), (@h2, CURDATE()-INTERVAL 59 DAY),
(@h2, CURDATE()-INTERVAL 58 DAY), (@h2, CURDATE()-INTERVAL 57 DAY),
(@h2, CURDATE()-INTERVAL 56 DAY), (@h2, CURDATE()-INTERVAL 55 DAY),
(@h2, CURDATE()-INTERVAL 53 DAY), (@h2, CURDATE()-INTERVAL 52 DAY),
(@h2, CURDATE()-INTERVAL 51 DAY), (@h2, CURDATE()-INTERVAL 50 DAY),
(@h2, CURDATE()-INTERVAL 49 DAY), (@h2, CURDATE()-INTERVAL 47 DAY),
(@h2, CURDATE()-INTERVAL 46 DAY), (@h2, CURDATE()-INTERVAL 45 DAY),
(@h2, CURDATE()-INTERVAL 44 DAY), (@h2, CURDATE()-INTERVAL 43 DAY),
(@h2, CURDATE()-INTERVAL 41 DAY), (@h2, CURDATE()-INTERVAL 40 DAY),
(@h2, CURDATE()-INTERVAL 39 DAY), (@h2, CURDATE()-INTERVAL 38 DAY),
(@h2, CURDATE()-INTERVAL 36 DAY), (@h2, CURDATE()-INTERVAL 35 DAY),
(@h2, CURDATE()-INTERVAL 34 DAY), (@h2, CURDATE()-INTERVAL 33 DAY),
(@h2, CURDATE()-INTERVAL 32 DAY), (@h2, CURDATE()-INTERVAL 31 DAY),
(@h2, CURDATE()-INTERVAL 29 DAY), (@h2, CURDATE()-INTERVAL 28 DAY),
(@h2, CURDATE()-INTERVAL 27 DAY), (@h2, CURDATE()-INTERVAL 26 DAY),
(@h2, CURDATE()-INTERVAL 24 DAY), (@h2, CURDATE()-INTERVAL 23 DAY),
(@h2, CURDATE()-INTERVAL 22 DAY), (@h2, CURDATE()-INTERVAL 21 DAY),
(@h2, CURDATE()-INTERVAL 19 DAY), (@h2, CURDATE()-INTERVAL 18 DAY),
(@h2, CURDATE()-INTERVAL 17 DAY), (@h2, CURDATE()-INTERVAL 16 DAY),
(@h2, CURDATE()-INTERVAL 14 DAY), (@h2, CURDATE()-INTERVAL 13 DAY),
(@h2, CURDATE()-INTERVAL 12 DAY), (@h2, CURDATE()-INTERVAL 11 DAY),
(@h2, CURDATE()-INTERVAL 10 DAY), (@h2, CURDATE()-INTERVAL 9 DAY),
(@h2, CURDATE()-INTERVAL 7 DAY),  (@h2, CURDATE()-INTERVAL 6 DAY),
(@h2, CURDATE()-INTERVAL 5 DAY),  (@h2, CURDATE()-INTERVAL 4 DAY),
(@h2, CURDATE()-INTERVAL 3 DAY),  (@h2, CURDATE()-INTERVAL 2 DAY),
(@h2, CURDATE()-INTERVAL 1 DAY),  (@h2, CURDATE());

-- Read Books: sporadic, about every 2-3 days
INSERT IGNORE INTO completion_logs (habit_id, completion_date) VALUES
(@h3, CURDATE()-INTERVAL 45 DAY), (@h3, CURDATE()-INTERVAL 43 DAY),
(@h3, CURDATE()-INTERVAL 40 DAY), (@h3, CURDATE()-INTERVAL 37 DAY),
(@h3, CURDATE()-INTERVAL 35 DAY), (@h3, CURDATE()-INTERVAL 32 DAY),
(@h3, CURDATE()-INTERVAL 30 DAY), (@h3, CURDATE()-INTERVAL 27 DAY),
(@h3, CURDATE()-INTERVAL 25 DAY), (@h3, CURDATE()-INTERVAL 22 DAY),
(@h3, CURDATE()-INTERVAL 19 DAY), (@h3, CURDATE()-INTERVAL 17 DAY),
(@h3, CURDATE()-INTERVAL 14 DAY), (@h3, CURDATE()-INTERVAL 11 DAY),
(@h3, CURDATE()-INTERVAL 9 DAY),  (@h3, CURDATE()-INTERVAL 6 DAY),
(@h3, CURDATE()-INTERVAL 3 DAY),  (@h3, CURDATE()-INTERVAL 1 DAY);

-- Weekly Gym: 3x per week pattern
INSERT IGNORE INTO completion_logs (habit_id, completion_date) VALUES
(@h4, CURDATE()-INTERVAL 42 DAY), (@h4, CURDATE()-INTERVAL 40 DAY),
(@h4, CURDATE()-INTERVAL 38 DAY), (@h4, CURDATE()-INTERVAL 35 DAY),
(@h4, CURDATE()-INTERVAL 33 DAY), (@h4, CURDATE()-INTERVAL 31 DAY),
(@h4, CURDATE()-INTERVAL 28 DAY), (@h4, CURDATE()-INTERVAL 26 DAY),
(@h4, CURDATE()-INTERVAL 24 DAY), (@h4, CURDATE()-INTERVAL 21 DAY),
(@h4, CURDATE()-INTERVAL 19 DAY), (@h4, CURDATE()-INTERVAL 17 DAY),
(@h4, CURDATE()-INTERVAL 14 DAY), (@h4, CURDATE()-INTERVAL 12 DAY),
(@h4, CURDATE()-INTERVAL 10 DAY), (@h4, CURDATE()-INTERVAL 7 DAY),
(@h4, CURDATE()-INTERVAL 5 DAY),  (@h4, CURDATE()-INTERVAL 3 DAY);

-- Old Meditation (archived): some old logs to show in heatmap if unarchived
INSERT IGNORE INTO completion_logs (habit_id, completion_date) VALUES
(@h5, CURDATE()-INTERVAL 90 DAY), (@h5, CURDATE()-INTERVAL 89 DAY),
(@h5, CURDATE()-INTERVAL 88 DAY), (@h5, CURDATE()-INTERVAL 85 DAY),
(@h5, CURDATE()-INTERVAL 84 DAY), (@h5, CURDATE()-INTERVAL 83 DAY),
(@h5, CURDATE()-INTERVAL 80 DAY), (@h5, CURDATE()-INTERVAL 79 DAY),
(@h5, CURDATE()-INTERVAL 75 DAY), (@h5, CURDATE()-INTERVAL 74 DAY);
